import { describe,expect,it } from 'vitest';
import { matchLeadReportRow,normalizeLocation,parseLeadReportCSV,parseWashingtonDohReport } from '@/lib/leadReportImport';
import type { Campus,Fixture } from '@/store/fixtureStore';

const campus:Campus={id:'campus-1',name:'North Campus',schoolDistrict:'Seattle Public Schools',school:'Lincoln High',address:''};
const fixture=(id:string,room:string):Fixture=>({id,campusId:campus.id,buildingId:'building-1',buildingName:'Science Building',floor:'2',roomNumber:room,nearestRoom:room,brand:'Elkay',model:'EZH2O',serialNumber:'',photoURL:'',modelPlatePhotoURL:'',lastMaintenanceDate:'2026-01-01',filterType:'',category:'BottleRefillStation',qualityRating:{pressure:3,cleanliness:3}});

describe('lead report extraction',()=>{
  it('extracts required fields from CSV',()=>{const[row]=parseLeadReportCSV('School District,School,Building,Floor,Room,Fixture Description,Sample ID,Sample Date,Lead Result,Unit\nSeattle Public Schools,Lincoln High,Science Building,2,Rm 205,Bottle Fill,S-1,2026-07-20,8.4,ppb');expect(row).toMatchObject({schoolDistrict:'Seattle Public Schools',school:'Lincoln High',building:'Science Building',floor:'2',room:'Rm 205',fixtureDescription:'Bottle Fill',sampleId:'S-1',sampleDate:'2026-07-20',resultValue:'8.4',resultUnit:'ppb'})});
  it('normalizes repeated floor labels while reading a report',()=>{const[row]=parseLeadReportCSV('School,Building,Floor,Room,Result\nRiverstone High School,Main Building,Floor Floor1,101,4');expect(row.floor).toBe('1')});
  it('normalizes common location and fixture synonyms',()=>{expect(normalizeLocation('Rm 205 Bubbler')).toBe('room 205 drinking fountain');expect(normalizeLocation('Bottle Fill')).toBe('bottle filler');expect(normalizeLocation('Tap')).toBe('faucet')});
  it('parses the Washington DOH drinking-water PDF layout',()=>{const pages=[[{y:680,items:[{x:166,text:'Lead in School Drinking Water Report'}]},{y:648,items:[{x:210,text:'Cedarhome Elementary School'}]},{y:431,items:[{x:72,text:'Date(s) collected: 2024'},{x:191,text:'-'},{x:195,text:'04'},{x:208,text:'-'},{x:212,text:'16'}]},{y:332,items:[{x:72,text:'391007'},{x:123,text:'Main'},{x:177,text:'Fountain/Tap'},{x:260,text:'Rm8'},{x:316,text:'2 of 2'},{x:397,text:'Tap'},{x:454,text:'left'},{x:507,text:'33'}]},{y:318,items:[{x:123,text:'Building'},{x:177,text:'Combo'}]}]];const[row]=parseWashingtonDohReport(pages,'stanwood-camano_school_district_cedarhome_elementary_school_lead_test_results.pdf');expect(row).toMatchObject({schoolDistrict:'Stanwood-Camano School District',school:'Cedarhome Elementary School',building:'Main Building',room:'8',fixtureType:'Faucet',sampleId:'391007',sampleDate:'2024-04-16',resultValue:'33',resultUnit:'ppb'})});
});
describe('existing fixture matching',()=>{
  it('returns high confidence for a unique prioritized location match',()=>{const[row]=parseLeadReportCSV('School District,School,Building,Floor,Room,Fixture Type,Result\nSeattle Public Schools,Lincoln High,Science Building,2,205,Bottle Refill Station,4.9');const match=matchLeadReportRow(row,[fixture('fixture-a','205'),fixture('fixture-b','210')],[campus]);expect(match.fixtureId).toBe('fixture-a');expect(match.status).toBe('high_confidence_match')});
  it('requires user choice for multiple equal matches',()=>{const[row]=parseLeadReportCSV('School,Building,Floor,Room,Result\nLincoln High,Science Building,2,205,4.9');const match=matchLeadReportRow(row,[fixture('fixture-a','205'),fixture('fixture-b','205')],[campus]);expect(match.status).toBe('multiple_matches');expect(match.alternatives).toHaveLength(2)});
  it('returns no match rather than creating a fixture',()=>{const[row]=parseLeadReportCSV('School,Building,Floor,Room,Result\nUnknown,Elsewhere,9,999,4.9');expect(matchLeadReportRow(row,[fixture('fixture-a','205')],[campus]).status).toBe('no_match')});
});
