/* eslint-disable @typescript-eslint/no-explicit-any */
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Download } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { formatPpb } from '@/lib/leadTesting';
import { PageHeader } from '@/components/layout/PageHeader';
import { LeadTestingModuleNav } from '@/components/LeadTestingModuleNav';
import { LeadReportUpload } from '@/components/LeadReportUpload';
import { Button } from '@/components/ui/button';

export default function LeadTestingUpload(){const navigate=useNavigate();const[params]=useSearchParams();const reviewUnresolved=params.get('review')==='unresolved';async function downloadMatches(){const db=supabase as any;const{data,error}=await db.from('lead_testing_report_rows').select('row_number,school_name,building_name,room,fixture_description,result_value,result_unit,normalized_result_ppb,match_status,match_confidence,confirmed_fixture_id,proposed_fixture_id,lead_testing_report_uploads(file_name)').is('deleted_at',null).order('report_upload_id').order('row_number');if(error){toast.error(error.message);return}const header=['Source Report','Row','School','Building','Room','Fixture Description','Lead Result (ppb)','Match Status','Matched Fixture ID'];const lines=(data??[]).map((row:any)=>{const upload=Array.isArray(row.lead_testing_report_uploads)?row.lead_testing_report_uploads[0]:row.lead_testing_report_uploads;return[upload?.file_name??'',row.row_number,row.school_name??'',row.building_name??'',row.room??'',row.fixture_description??'',formatPpb(row.normalized_result_ppb),row.match_status,row.confirmed_fixture_id??row.proposed_fixture_id??'']});const csv=[header,...lines].map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='lead-report-matching-results.csv';link.click();URL.revokeObjectURL(link.href)}return <div className="page-shell"><PageHeader title={reviewUnresolved?'Unresolved Matches':'Upload Test Report'} subtitle={reviewUnresolved?'Review and confirm unmatched laboratory results':'Extract, match, review, and import laboratory results'} backTo="/lead-testing/results" action={<Button size="sm" variant="outline" onClick={()=>void downloadMatches()}><Download className="mr-1 h-4 w-4"/>Download</Button>}/><LeadTestingModuleNav/><LeadReportUpload reviewUnresolved={reviewUnresolved} onImported={()=>navigate('/lead-testing/results')}/></div>}
