import { useState } from 'react';
import { ListChecks, Search } from 'lucide-react';
import { toast } from 'sonner';
import { useFixtureStore } from '@/store/fixtureStore';
import { useLeadTesting } from '@/hooks/useLeadTesting';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useOrganization } from '@/contexts/OrganizationContext';

export function BulkSampling(){
  const {isSchoolDistrict}=useOrganization();
  const {fixtures,campuses}=useFixtureStore();const lead=useLeadTesting();const[district,setDistrict]=useState('');const[schoolId,setSchoolId]=useState('');const[fixtureQuery,setFixtureQuery]=useState('');const[selected,setSelected]=useState<string[]>([]);const[date,setDate]=useState('');const[collector,setCollector]=useState('');const[method,setMethod]=useState('first_draw_250ml');const[description,setDescription]=useState('');const[notes,setNotes]=useState('');const[busy,setBusy]=useState(false);
  const districtName=(value:string|undefined)=>value?.trim()||'District not recorded';
  const districts=[...new Set(campuses.map(campus=>districtName(campus.schoolDistrict)))].sort();
  const districtSchools=isSchoolDistrict?campuses.filter(campus=>districtName(campus.schoolDistrict)===district):campuses;
  const schoolFixtures=fixtures.filter(fixture=>fixture.campusId===schoolId);
  const samplingFixtures=schoolFixtures.filter(fixture=>['not_started','scheduled'].includes(fixture.currentLeadTestingStatus??'not_started'));
  const normalizedQuery=fixtureQuery.trim().toLowerCase();
  const visibleFixtures=samplingFixtures.filter(fixture=>!normalizedQuery||[fixture.id,fixture.buildingName,fixture.floor,fixture.roomNumber,fixture.nearestRoom,fixture.category,fixture.brand,fixture.model].filter(Boolean).join(' ').toLowerCase().includes(normalizedQuery));
  function toggleAll(checked:boolean){setSelected(checked?samplingFixtures.map(fixture=>fixture.id):[])}
  async function complete(){setBusy(true);try{for(const fixtureId of selected)await lead.createRound({fixtureId,roundType:'initial_test',sampleDrawDate:date,collector,method,methodDescription:description,notes});toast.success(`Sampling documented for ${selected.length} fixtures`);setSelected([]);setDate('');setNotes('')}catch(error){toast.error(error instanceof Error?error.message:'Could not document sampling')}finally{setBusy(false)}}
  const fixtureStep=isSchoolDistrict?3:2;const documentStep=isSchoolDistrict?4:3;
  return <div className="space-y-4">{isSchoolDistrict&&<div className="card-section"><div className="panel-header"><h2 className="font-semibold">1. Select School District</h2></div><div className="panel-body"><Select value={district} onValueChange={value=>{setDistrict(value);setSchoolId('');setFixtureQuery('');setSelected([])}}><SelectTrigger><SelectValue placeholder="Select a school district"/></SelectTrigger><SelectContent>{districts.map(name=><SelectItem key={name} value={name}>{name}</SelectItem>)}</SelectContent></Select></div></div>}
    {(!isSchoolDistrict||district)&&<div className="card-section"><div className="panel-header"><h2 className="font-semibold">{isSchoolDistrict?'2. Select School':'1. Select Campus'}</h2></div><div className="panel-body"><Select value={schoolId} onValueChange={value=>{setSchoolId(value);setFixtureQuery('');setSelected([])}}><SelectTrigger><SelectValue placeholder={isSchoolDistrict?'Select a school':'Select a campus'}/></SelectTrigger><SelectContent>{districtSchools.map(campus=><SelectItem key={campus.id} value={campus.id}>{isSchoolDistrict?campus.school:campus.name}</SelectItem>)}</SelectContent></Select></div></div>}
    {schoolId&&<div className="card-section"><div className="panel-header"><div><h2 className="font-semibold">{fixtureStep}. Select Fixtures</h2><p className="mt-0.5 text-xs text-muted-foreground">{samplingFixtures.length} fixtures require sampling</p></div><label className="flex items-center gap-2 text-xs"><Checkbox checked={samplingFixtures.length>0&&selected.length===samplingFixtures.length} onCheckedChange={checked=>toggleAll(checked===true)}/>Select All</label></div><div className="panel-body"><div className="relative mb-3"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={fixtureQuery} onChange={event=>setFixtureQuery(event.target.value)} placeholder="Search building, floor, room, type, or fixture ID…"/></div><Button type="button" variant="outline" className="mb-3 w-full" disabled={!samplingFixtures.length} onClick={()=>toggleAll(true)}><ListChecks className="mr-2 h-4 w-4"/>Select All {samplingFixtures.length} Fixtures Needing Sampling</Button><div className="max-h-72 space-y-2 overflow-y-auto">{visibleFixtures.map(fixture=><label key={fixture.id} className="list-row cursor-pointer"><Checkbox checked={selected.includes(fixture.id)} onCheckedChange={checked=>setSelected(current=>checked?[...new Set([...current,fixture.id])]:current.filter(id=>id!==fixture.id))}/><span className="text-xs"><b>{fixture.buildingName} · Floor {fixture.floor} · Room {fixture.roomNumber}</b><br/><span className="text-muted-foreground">{fixture.category} · {fixture.id}</span></span></label>)}{!samplingFixtures.length&&<p className="py-5 text-center text-sm text-muted-foreground">All fixtures at this {isSchoolDistrict?'school':'campus'} have already entered the sampling workflow.</p>}{samplingFixtures.length>0&&!visibleFixtures.length&&<p className="py-5 text-center text-sm text-muted-foreground">No fixtures match this search.</p>}</div></div></div>}
    {selected.length>0&&<div className="card-section"><div className="panel-header"><h2 className="font-semibold">{documentStep}. Document Sampling · {selected.length} fixtures</h2></div><div className="panel-body space-y-3"><Field label="Sample Draw Date"><Input type="date" value={date} onChange={event=>setDate(event.target.value)}/></Field><Field label="Collector"><Input value={collector} onChange={event=>setCollector(event.target.value)}/><p className="text-[11px] text-muted-foreground">Examples: DOH, External Contractor, {isSchoolDistrict?'School District Staff':'University of Washington Staff'}, John Smith</p></Field><Field label="Sampling Method"><Select value={method} onValueChange={setMethod}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="first_draw_250ml">First Draw (250 mL)</SelectItem><SelectItem value="flush_sample_30_seconds">Flush Sample (30-second flush)</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select></Field>{method==='other'&&<Field label="Other method description (optional)"><Input value={description} onChange={event=>setDescription(event.target.value)}/></Field>}<Field label="Notes (optional)"><Textarea value={notes} onChange={event=>setNotes(event.target.value)}/></Field><Button className="w-full" disabled={busy||!date||!collector.trim()} onClick={complete}>{busy?`Creating ${selected.length} sampling records…`:`Create Sampling Records for ${selected.length} Fixtures`}</Button></div></div>}
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
